### ISSUE TITLE
It's absolutely amazing!

### ISSUE THREAD

**Issue by LuciNyan** [hsiaosiyuan0/slowjs#6]
Hey @hsiaosiyuan0, this isn't a bug report issue, I just wanted to let you know that this repo is absolutely amazing. I've been searching for something like this for so long and I'm so grateful for it! Thank you so, so much! <3

**Comment by hsiaosiyuan0** [comment]
thank you so much, your words of encouragement will let me progress

**Comment by hsiaosiyuan0** [comment]
I'll close this issue temporarily, feel free to reopen it if you have any suggestions
